version: '3.3'

volumes:
  static:
  

services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - static:/static
    command: sh -c "python manage.py migrate && python manage.py collectstatic -c --noinput && cp -r /app/collected_static/. /static/ && python manage.py loaddata ./data.json && gunicorn --bind 0.0.0.0:8000 performers.wsgi"
    restart: unless-stopped

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
    depends_on:
      - backend
    restart: unless-stopped